# Generated by Django 4.0.6 on 2022-07-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=6),
        ),
    ]
